# 电池电量报告间隔时间单位是秒
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# 增加键盘消抖
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# 增加键盘的 BLE 无线电的发射功率
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_POINTING=y=y

# ===================== 蓝牙参数配置 =====================
# 最大连接间隔（1.25ms 单位，9=11.25ms）
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
# 连接延迟（主机跳过的连接事件数）
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
# ACL数据包发送缓冲区数量（ZMK 4.1 要求 BT_BUF_EVT_RX_COUNT > BT_BUF_ACL_TX_COUNT）
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_BUF_EVT_RX_COUNT=64
# L2CAP层发送缓冲区数量
CONFIG_BT_L2CAP_TX_BUF_COUNT=32
# 蓝牙发射功率+8dBm（最大）
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# 启用蓝牙电池服务 
CONFIG_BT_BAS=y

# ===================== 自动休眠相关 =====================
# 自动休眠
CONFIG_ZMK_SLEEP=y
# （已注释）进入自动休眠的时间（单位：ms）
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
#进入空闲状态的时间（单位：ms）
CONFIG_ZMK_IDLE_TIMEOUT=15000

# ===================== BLE实验性功能 =====================
# 启用BLE实验性连接特性
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# 主控端获取从端电池电量
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# 主控端代理电池电量
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# 行为队列大小，提升宏/组合键响应能力
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

#防抖时间，如果追求低延迟，可以适当缩短，如果发生连击可适当延长
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y
